### ISSUE TITLE
Where is the difference?

### ISSUE THREAD

**Issue by diggit** [lukascechovic/voron-v01-POM-fix#1]
Hi,
I have V0.1 build from LDO kit manufactured in late 2021.
With every Z axis part from kit and 0.375 A motor current, I am pushing 400g tube of grease at full Z travel with boosted speed and acceleration:
```
max_z_velocity: 40
max_z_accel: 80
```
No issues.

The only difference I did was small change in assembly order.

At fist I mounted POM nut to plastic part of carriage, assembled whole Z axis and as the last step, mounted plastic part carrying nut to Z carriage extrusion.

In action...

https://user-images.githubusercontent.com/512025/177050641-d4f084af-8b62-4641-97a4-88202a234604.mp4

I am still not convinced, that any modifications are necessary. :shrug:

**Comment by lukascechovic** [comment]
Hello, thx for message. Thats great your printer is working well. Whole Z assemble is done by mechanical engineers and its not imo suitable for reliable 3d printing. What I wanna say printed parts for Z plays huge role here (assemble too ofc) and you can end up with 3d pritned parts with slight deformation (non noticeable by eye) and using ptfe coated leadcrew with plastic nut takes away tolerance needed for those occasions. I have random v0.1 kit with non ptfe coated leadscrew with no problems at all from start. And yes most of people don't have problems but there was that time lots with problems. Even today another guy wrote me in search for solution. BR

**Comment by diggit** [comment]
We can only hope, that V0.2 will improve this part.
